"""agregar_medio_pago_pedido_y_tabla_cheques

Revision ID: 014336a399a5
Revises: 5d69193ba885
Create Date: 2025-12-31 13:50:36.418352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '014336a399a5'
down_revision: Union[str, None] = '5d69193ba885'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cheques',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('estado_id', sa.Integer(), nullable=False),
    sa.Column('numero_cheque', sa.String(), nullable=False),
    sa.Column('banco', sa.String(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_emision', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_vencimiento', sa.DateTime(timezone=True), nullable=False),
    sa.Column('librador_nombre', sa.String(), nullable=False),
    sa.Column('librador_rut', sa.String(), nullable=True),
    sa.Column('fecha_recepcion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_deposito', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_cobro', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['estado_id'], ['estados_cheque.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cheques_id'), 'cheques', ['id'], unique=False)
    op.create_index(op.f('ix_cheques_numero_cheque'), 'cheques', ['numero_cheque'], unique=False)
    op.add_column('pedidos', sa.Column('medio_pago_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pedidos', 'medios_pago', ['medio_pago_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pedidos', type_='foreignkey')
    op.drop_column('pedidos', 'medio_pago_id')
    op.drop_index(op.f('ix_cheques_numero_cheque'), table_name='cheques')
    op.drop_index(op.f('ix_cheques_id'), table_name='cheques')
    op.drop_table('cheques')
    # ### end Alembic commands ###
