"""agregar campo imagen_url a productos

Revision ID: 042fe92e014b
Revises: 2933e69a77f2
Create Date: 2025-11-21 14:30:01.520336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '042fe92e014b'
down_revision: Union[str, None] = '2933e69a77f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('imagen_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productos', 'imagen_url')
    # ### end Alembic commands ###
