"""Agregar campo lote_proveedor a tabla lotes

Revision ID: 0cf23bf5f336
Revises: 1cce6302da6a
Create Date: 2026-01-05 20:54:40.851483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cf23bf5f336'
down_revision: Union[str, None] = '1cce6302da6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lotes', sa.Column('lote_proveedor', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lotes', 'lote_proveedor')
    # ### end Alembic commands ###
