"""sincronizar email NOT NULL y otros cambios pendientes

Revision ID: 19e80f61a62d
Revises: 9a76383fabc7
Create Date: 2026-02-24 14:13:10.439499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19e80f61a62d'
down_revision: Union[str, None] = '9a76383fabc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Migración simplificada: Solo cambios críticos de email NOT NULL
    # Los cambios de índices de locales, productos se omiten por conflictos multi-tenant
    
    # 1. Aplicar NOT NULL a email en clientes (ya limpiamos los registros con NULL)
    op.alter_column('clientes', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    
    # 2. Actualizar constraint único de email a nivel tenant (si existe el índice anterior, eliminarlo)
    try:
        op.drop_index('ix_clientes_tenant_email_unique', table_name='clientes', postgresql_where='(email IS NOT NULL)')
    except:
        pass  # El índice podría no existir
    
    # 3. Crear constraint único compuesto (tenant_id, email)
    try:
        op.create_unique_constraint('uq_cliente_tenant_email', 'clientes', ['tenant_id', 'email'])
    except:
        pass  # El constraint podría ya existir
    
    # 4. Agregar índice a proveedores.tenant_id para performance
    try:
        op.create_index(op.f('ix_proveedores_tenant_id'), 'proveedores', ['tenant_id'], unique=False)
    except:
        pass  # El índice podría ya existir
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Revertir cambios simplificados
    
    # Revertir índice de proveedores
    try:
        op.drop_index(op.f('ix_proveedores_tenant_id'), table_name='proveedores')
    except:
        pass
    
    # Revertir constraint único
    try:
        op.drop_constraint('uq_cliente_tenant_email', 'clientes', type_='unique')
    except:
        pass
    
    # Recrear índice anterior (si existía)
    try:
        op.create_index('ix_clientes_tenant_email_unique', 'clientes', ['tenant_id', 'email'], unique=False, postgresql_where='(email IS NOT NULL)')
    except:
        pass
    
    # Revertir NOT NULL en email
    op.alter_column('clientes', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
