"""Sistema enrolamiento WMS

Revision ID: 1cce6302da6a
Revises: f174fd5be22a
Create Date: 2026-01-05 17:21:17.125973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cce6302da6a'
down_revision: Union[str, None] = 'f174fd5be22a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estados_enrolamiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estados_enrolamiento_codigo'), 'estados_enrolamiento', ['codigo'], unique=True)
    op.create_index(op.f('ix_estados_enrolamiento_id'), 'estados_enrolamiento', ['id'], unique=False)
    op.create_table('tipos_vehiculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipos_vehiculo_codigo'), 'tipos_vehiculo', ['codigo'], unique=True)
    op.create_index(op.f('ix_tipos_vehiculo_id'), 'tipos_vehiculo', ['id'], unique=False)
    op.create_table('ubicaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('capacidad_maxima', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ubicaciones_codigo'), 'ubicaciones', ['codigo'], unique=True)
    op.create_index(op.f('ix_ubicaciones_id'), 'ubicaciones', ['id'], unique=False)
    op.create_table('enrolamientos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_vehiculo_id', sa.Integer(), nullable=False),
    sa.Column('patente', sa.String(), nullable=False),
    sa.Column('chofer', sa.String(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('numero_documento', sa.String(), nullable=False),
    sa.Column('estado_id', sa.Integer(), nullable=False),
    sa.Column('usuario_registro_id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_termino', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['estado_id'], ['estados_enrolamiento.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tipo_vehiculo_id'], ['tipos_vehiculo.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['usuario_registro_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enrolamientos_id'), 'enrolamientos', ['id'], unique=False)
    op.create_index(op.f('ix_enrolamientos_patente'), 'enrolamientos', ['patente'], unique=False)
    op.create_table('lotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_lote', sa.String(), nullable=False),
    sa.Column('enrolamiento_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('ubicacion_id', sa.Integer(), nullable=False),
    sa.Column('qr_original', sa.String(), nullable=True),
    sa.Column('qr_propio', sa.String(), nullable=False),
    sa.Column('peso_original', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('peso_actual', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('fecha_vencimiento', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_fabricacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('disponible_venta', sa.Boolean(), nullable=True),
    sa.Column('vendido', sa.Boolean(), nullable=True),
    sa.Column('foto_etiqueta', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['enrolamiento_id'], ['enrolamientos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ubicacion_id'], ['ubicaciones.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lotes_codigo_lote'), 'lotes', ['codigo_lote'], unique=True)
    op.create_index(op.f('ix_lotes_id'), 'lotes', ['id'], unique=False)
    op.create_index(op.f('ix_lotes_qr_propio'), 'lotes', ['qr_propio'], unique=True)
    op.add_column('items_pedido', sa.Column('lote_id', sa.Integer(), nullable=True))
    op.drop_constraint('uix_item_pedido_producto', 'items_pedido', type_='unique')
    op.create_unique_constraint('uix_item_pedido_producto_lote', 'items_pedido', ['pedido_id', 'producto_id', 'lote_id'])
    op.create_foreign_key(None, 'items_pedido', 'lotes', ['lote_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'items_pedido', type_='foreignkey')
    op.drop_constraint('uix_item_pedido_producto_lote', 'items_pedido', type_='unique')
    op.create_unique_constraint('uix_item_pedido_producto', 'items_pedido', ['pedido_id', 'producto_id'])
    op.drop_column('items_pedido', 'lote_id')
    op.drop_index(op.f('ix_lotes_qr_propio'), table_name='lotes')
    op.drop_index(op.f('ix_lotes_id'), table_name='lotes')
    op.drop_index(op.f('ix_lotes_codigo_lote'), table_name='lotes')
    op.drop_table('lotes')
    op.drop_index(op.f('ix_enrolamientos_patente'), table_name='enrolamientos')
    op.drop_index(op.f('ix_enrolamientos_id'), table_name='enrolamientos')
    op.drop_table('enrolamientos')
    op.drop_index(op.f('ix_ubicaciones_id'), table_name='ubicaciones')
    op.drop_index(op.f('ix_ubicaciones_codigo'), table_name='ubicaciones')
    op.drop_table('ubicaciones')
    op.drop_index(op.f('ix_tipos_vehiculo_id'), table_name='tipos_vehiculo')
    op.drop_index(op.f('ix_tipos_vehiculo_codigo'), table_name='tipos_vehiculo')
    op.drop_table('tipos_vehiculo')
    op.drop_index(op.f('ix_estados_enrolamiento_id'), table_name='estados_enrolamiento')
    op.drop_index(op.f('ix_estados_enrolamiento_codigo'), table_name='estados_enrolamiento')
    op.drop_table('estados_enrolamiento')
    # ### end Alembic commands ###
