"""Agregar campos de credito a clientes

Revision ID: 1d53a584b8aa
Revises: 5f16b24fa823
Create Date: 2025-12-31 18:55:17.041136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d53a584b8aa'
down_revision: Union[str, None] = '5f16b24fa823'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Agregar campos de crédito a la tabla clientes
    op.add_column('clientes', sa.Column('limite_credito', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0.00'))
    op.add_column('clientes', sa.Column('credito_usado', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0.00'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Eliminar campos de crédito de la tabla clientes
    op.drop_column('clientes', 'credito_usado')
    op.drop_column('clientes', 'limite_credito')
    # ### end Alembic commands ###
