"""add_configuracion_landing_display_options

Revision ID: 20f6fa6fd6b1
Revises: 82a9a74af741
Create Date: 2026-02-17 16:47:25.526628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20f6fa6fd6b1'
down_revision: Union[str, None] = '82a9a74af741'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Solo agregar columnas a configuracion_landing
    op.add_column('configuracion_landing', sa.Column('mostrar_precios', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('configuracion_landing', sa.Column('mostrar_stock', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('configuracion_landing', sa.Column('habilitar_carrito', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Solo eliminar columnas de configuracion_landing
    op.drop_column('configuracion_landing', 'habilitar_carrito')
    op.drop_column('configuracion_landing', 'mostrar_stock')
    op.drop_column('configuracion_landing', 'mostrar_precios')
    # ### end Alembic commands ###
