"""add_precio_minimo_kg_to_precios_proveedor

Revision ID: 239399aa0903
Revises: 2d9d9c7d73d7
Create Date: 2026-03-10 19:38:52.565896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '239399aa0903'
down_revision: Union[str, None] = '2d9d9c7d73d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('precios_proveedor', sa.Column('precio_minimo_kg', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('precios_proveedor', 'precio_minimo_kg')
    # ### end Alembic commands ###
