"""add_movimientos_inventario_table

Revision ID: 25d2067d81f2
Revises: 787f179b0bed
Create Date: 2025-11-24 17:08:04.471053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25d2067d81f2'
down_revision: Union[str, None] = '787f179b0bed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movimientos_inventario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('local_origen_id', sa.Integer(), nullable=True),
    sa.Column('local_destino_id', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('tipo_movimiento', sa.String(), nullable=False),
    sa.Column('referencia_id', sa.Integer(), nullable=True),
    sa.Column('notas', sa.String(), nullable=True),
    sa.Column('usuario', sa.String(), nullable=True),
    sa.Column('fecha_movimiento', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['local_destino_id'], ['locales.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['local_origen_id'], ['locales.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimientos_inventario_fecha_movimiento'), 'movimientos_inventario', ['fecha_movimiento'], unique=False)
    op.create_index(op.f('ix_movimientos_inventario_id'), 'movimientos_inventario', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movimientos_inventario_id'), table_name='movimientos_inventario')
    op.drop_index(op.f('ix_movimientos_inventario_fecha_movimiento'), table_name='movimientos_inventario')
    op.drop_table('movimientos_inventario')
    # ### end Alembic commands ###
