"""Agregar campo codigo a tabla locales

Revision ID: 2933e69a77f2
Revises: 921430423f7b
Create Date: 2025-11-20 18:54:03.947656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2933e69a77f2'
down_revision: Union[str, None] = '921430423f7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Paso 1: Agregar columna como nullable
    op.add_column('locales', sa.Column('codigo', sa.String(), nullable=True))
    
    # Paso 2: Poblar valores para registros existentes basados en el nombre
    op.execute("""
        UPDATE locales 
        SET codigo = CASE 
            WHEN LOWER(nombre) LIKE '%lampa%' THEN 'LAMPA'
            WHEN LOWER(nombre) LIKE '%tiltil%' THEN 'TILTIL'
            WHEN LOWER(nombre) LIKE '%boulevard%' THEN 'BOULEVARD'
            ELSE UPPER(REPLACE(nombre, ' ', '_'))
        END
        WHERE codigo IS NULL
    """)
    
    # Paso 3: Hacer la columna NOT NULL
    op.alter_column('locales', 'codigo', nullable=False)
    
    # Paso 4: Crear índice único
    op.create_index(op.f('ix_locales_codigo'), 'locales', ['codigo'], unique=True)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_locales_codigo'), table_name='locales')
    op.drop_column('locales', 'codigo')
    # ### end Alembic commands ###
