"""rut_unico_por_tenant_en_proveedores

Revision ID: 2d9d9c7d73d7
Revises: 4a1ecd0955dc
Create Date: 2026-03-10 17:14:21.917993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d9d9c7d73d7'
down_revision: Union[str, None] = '4a1ecd0955dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_proveedores_rut', table_name='proveedores')
    op.create_index(op.f('ix_proveedores_rut'), 'proveedores', ['rut'], unique=False)
    op.create_unique_constraint('uix_proveedor_tenant_rut', 'proveedores', ['tenant_id', 'rut'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_proveedor_tenant_rut', 'proveedores', type_='unique')
    op.drop_index(op.f('ix_proveedores_rut'), table_name='proveedores')
    op.create_index('ix_proveedores_rut', 'proveedores', ['rut'], unique=False)
    # ### end Alembic commands ###
