"""verificacion final sincronizacion

Revision ID: 34797116272a
Revises: 19e80f61a62d
Create Date: 2026-02-24 14:37:40.411192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34797116272a'
down_revision: Union[str, None] = '19e80f61a62d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_locales_tenant_codigo_unique', table_name='locales')
    op.drop_index('ix_locales_tenant_nombre_unique', table_name='locales')
    op.create_unique_constraint('uq_local_tenant_codigo', 'locales', ['tenant_id', 'codigo'])
    op.create_unique_constraint('uq_local_tenant_nombre', 'locales', ['tenant_id', 'nombre'])
    op.drop_index('ix_productos_tenant_sku_unique', table_name='productos')
    op.create_unique_constraint('uq_producto_tenant_sku', 'productos', ['tenant_id', 'sku'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_producto_tenant_sku', 'productos', type_='unique')
    op.create_index('ix_productos_tenant_sku_unique', 'productos', ['tenant_id', 'sku'], unique=False)
    op.drop_constraint('uq_local_tenant_nombre', 'locales', type_='unique')
    op.drop_constraint('uq_local_tenant_codigo', 'locales', type_='unique')
    op.create_index('ix_locales_tenant_nombre_unique', 'locales', ['tenant_id', 'nombre'], unique=False)
    op.create_index('ix_locales_tenant_codigo_unique', 'locales', ['tenant_id', 'codigo'], unique=False)
    # ### end Alembic commands ###
