"""add cantidad_recibida to item_solicitud_transferencia

Revision ID: 34d507d725cf
Revises: 8c8efa23f3b8
Create Date: 2026-03-02 23:47:48.482883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34d507d725cf'
down_revision: Union[str, None] = '8c8efa23f3b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items_solicitud_transferencia', sa.Column('cantidad_recibida', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items_solicitud_transferencia', 'cantidad_recibida')
    # ### end Alembic commands ###
