"""remove_unique_pedido_id_notas_credito

Revision ID: 38d371de575b
Revises: 3d663fa2d8bd
Create Date: 2026-03-24 20:33:31.688290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38d371de575b'
down_revision: Union[str, None] = '3d663fa2d8bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notas_credito_pedido_id', table_name='notas_credito')
    op.create_index(op.f('ix_notas_credito_pedido_id'), 'notas_credito', ['pedido_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notas_credito_pedido_id'), table_name='notas_credito')
    op.create_index('ix_notas_credito_pedido_id', 'notas_credito', ['pedido_id'], unique=False)
    # ### end Alembic commands ###
