"""add_cliente_notification_preferences

Revision ID: 38d95567fc0c
Revises: 5f21c9c60706
Create Date: 2026-03-26 15:50:37.234890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38d95567fc0c'
down_revision: Union[str, None] = '5f21c9c60706'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente_notification_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('canal', sa.String(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('token_unsub', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cliente_id', 'canal', name='uq_cliente_canal')
    )
    op.create_index(op.f('ix_cliente_notification_preferences_cliente_id'), 'cliente_notification_preferences', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_cliente_notification_preferences_id'), 'cliente_notification_preferences', ['id'], unique=False)
    op.create_index(op.f('ix_cliente_notification_preferences_token_unsub'), 'cliente_notification_preferences', ['token_unsub'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cliente_notification_preferences_token_unsub'), table_name='cliente_notification_preferences')
    op.drop_index(op.f('ix_cliente_notification_preferences_id'), table_name='cliente_notification_preferences')
    op.drop_index(op.f('ix_cliente_notification_preferences_cliente_id'), table_name='cliente_notification_preferences')
    op.drop_table('cliente_notification_preferences')
    # ### end Alembic commands ###
