"""Agregar sistema de puntos por cliente

Revision ID: 38f1ff2192cd
Revises: 1d53a584b8aa
Create Date: 2025-12-31 19:39:38.425264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38f1ff2192cd'
down_revision: Union[str, None] = '1d53a584b8aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('puntos_cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('puntos_disponibles', sa.Integer(), nullable=False),
    sa.Column('puntos_totales_ganados', sa.Integer(), nullable=False),
    sa.Column('puntos_totales_usados', sa.Integer(), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cliente_id', name='uq_puntos_cliente_id')
    )
    op.create_index('ix_puntos_cliente_disponibles', 'puntos_cliente', ['puntos_disponibles'], unique=False)
    op.create_index(op.f('ix_puntos_cliente_id'), 'puntos_cliente', ['id'], unique=False)
    op.create_table('movimientos_puntos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('tipo_movimiento', sa.Enum('GANADOS', 'USADOS', 'VENCIDOS', 'AJUSTE', name='tipomovimientopuntos'), nullable=False),
    sa.Column('puntos', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('fecha_movimiento', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias_producto.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_movimientos_puntos_cliente_fecha', 'movimientos_puntos', ['cliente_id', 'fecha_movimiento'], unique=False)
    op.create_index(op.f('ix_movimientos_puntos_id'), 'movimientos_puntos', ['id'], unique=False)
    op.create_index('ix_movimientos_puntos_pedido', 'movimientos_puntos', ['pedido_id'], unique=False)
    op.create_index('ix_movimientos_puntos_tipo', 'movimientos_puntos', ['tipo_movimiento'], unique=False)
    op.add_column('pedidos', sa.Column('puntos_ganados', sa.Integer(), nullable=True))
    op.add_column('pedidos', sa.Column('puntos_usados', sa.Integer(), nullable=True))
    op.add_column('pedidos', sa.Column('descuento_puntos', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pedidos', 'descuento_puntos')
    op.drop_column('pedidos', 'puntos_usados')
    op.drop_column('pedidos', 'puntos_ganados')
    op.drop_index('ix_movimientos_puntos_tipo', table_name='movimientos_puntos')
    op.drop_index('ix_movimientos_puntos_pedido', table_name='movimientos_puntos')
    op.drop_index(op.f('ix_movimientos_puntos_id'), table_name='movimientos_puntos')
    op.drop_index('ix_movimientos_puntos_cliente_fecha', table_name='movimientos_puntos')
    op.drop_table('movimientos_puntos')
    op.drop_index(op.f('ix_puntos_cliente_id'), table_name='puntos_cliente')
    op.drop_index('ix_puntos_cliente_disponibles', table_name='puntos_cliente')
    op.drop_table('puntos_cliente')
    # ### end Alembic commands ###
