"""tabla locales_cliente para sucursales de cliente

Revision ID: 3b8f877b1bbf
Revises: 34d507d725cf
Create Date: 2026-03-06 12:07:12.152708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b8f877b1bbf'
down_revision: Union[str, None] = '34d507d725cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locales_cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=False),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locales_cliente_cliente_id'), 'locales_cliente', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_locales_cliente_id'), 'locales_cliente', ['id'], unique=False)
    op.drop_column('clientes', 'comuna')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('comuna', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_locales_cliente_id'), table_name='locales_cliente')
    op.drop_index(op.f('ix_locales_cliente_cliente_id'), table_name='locales_cliente')
    op.drop_table('locales_cliente')
    # ### end Alembic commands ###
