"""add_devoluciones_tables

Revision ID: 3d663fa2d8bd
Revises: 88cbf2da3ffb
Create Date: 2026-03-24 20:32:07.934271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d663fa2d8bd'
down_revision: Union[str, None] = '88cbf2da3ffb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devoluciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('nota_credito_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('fecha_devolucion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['nota_credito_id'], ['notas_credito.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devoluciones_id'), 'devoluciones', ['id'], unique=False)
    op.create_index(op.f('ix_devoluciones_pedido_id'), 'devoluciones', ['pedido_id'], unique=False)
    op.create_index(op.f('ix_devoluciones_tenant_id'), 'devoluciones', ['tenant_id'], unique=False)
    op.create_table('items_devolucion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('devolucion_id', sa.Integer(), nullable=False),
    sa.Column('item_pedido_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad_devuelta', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('local_destino_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['devolucion_id'], ['devoluciones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_pedido_id'], ['items_pedido.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['local_destino_id'], ['locales.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_devolucion_devolucion_id'), 'items_devolucion', ['devolucion_id'], unique=False)
    op.create_index(op.f('ix_items_devolucion_id'), 'items_devolucion', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_devolucion_id'), table_name='items_devolucion')
    op.drop_index(op.f('ix_items_devolucion_devolucion_id'), table_name='items_devolucion')
    op.drop_table('items_devolucion')
    op.drop_index(op.f('ix_devoluciones_tenant_id'), table_name='devoluciones')
    op.drop_index(op.f('ix_devoluciones_pedido_id'), table_name='devoluciones')
    op.drop_index(op.f('ix_devoluciones_id'), table_name='devoluciones')
    op.drop_table('devoluciones')
    # ### end Alembic commands ###
