"""crear solicitudes_transferencia

Revision ID: 49a92ddfe08e
Revises: 143c02017f16
Create Date: 2026-02-26 16:50:30.022405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49a92ddfe08e'
down_revision: Union[str, None] = '143c02017f16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitudes_transferencia',
    sa.Column('solicitud_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('local_origen_id', sa.Integer(), nullable=False),
    sa.Column('local_destino_id', sa.Integer(), nullable=False),
    sa.Column('usuario_solicitante_id', sa.Integer(), nullable=False),
    sa.Column('estado_id', sa.Integer(), nullable=False),
    sa.Column('nota', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['estado_id'], ['estados_enrolamiento.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['local_destino_id'], ['locales.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['local_origen_id'], ['locales.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_solicitante_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('solicitud_id')
    )
    op.create_index(op.f('ix_solicitudes_transferencia_solicitud_id'), 'solicitudes_transferencia', ['solicitud_id'], unique=False)
    op.create_table('items_solicitud_transferencia',
    sa.Column('solicitud_item_id', sa.Integer(), nullable=False),
    sa.Column('solicitud_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad_solicitada', sa.Integer(), nullable=False),
    sa.Column('cantidad_aprobada', sa.Integer(), nullable=True),
    sa.Column('movimiento_inventario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['movimiento_inventario_id'], ['movimientos_inventario.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitudes_transferencia.solicitud_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('solicitud_item_id')
    )
    op.create_index(op.f('ix_items_solicitud_transferencia_solicitud_item_id'), 'items_solicitud_transferencia', ['solicitud_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_solicitud_transferencia_solicitud_item_id'), table_name='items_solicitud_transferencia')
    op.drop_table('items_solicitud_transferencia')
    op.drop_index(op.f('ix_solicitudes_transferencia_solicitud_id'), table_name='solicitudes_transferencia')
    op.drop_table('solicitudes_transferencia')
    # ### end Alembic commands ###
