"""add_google_sheet_id_to_tenants

Revision ID: 4a1ecd0955dc
Revises: 5a8d8b2cf3b3
Create Date: 2026-03-10 11:22:32.002947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a1ecd0955dc'
down_revision: Union[str, None] = '5a8d8b2cf3b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('google_sheet_id', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'google_sheet_id')
    # ### end Alembic commands ###
