"""add_correlativo_pedido_to_tenants

Revision ID: 51165dcf3d23
Revises: 20f6fa6fd6b1
Create Date: 2026-02-17 17:19:21.272268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51165dcf3d23'
down_revision: Union[str, None] = '20f6fa6fd6b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Agregar columna correlativo_pedido a tabla tenants
    op.add_column('tenants', sa.Column('correlativo_pedido', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Eliminar columna correlativo_pedido de tabla tenants
    op.drop_column('tenants', 'correlativo_pedido')
    # ### end Alembic commands ###
