"""Agregar campos tributarios a clientes y pedidos

Revision ID: 55ae0810b1bc
Revises: 474c74ee6ce3
Create Date: 2026-01-14 17:13:30.596557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55ae0810b1bc'
down_revision: Union[str, None] = '474c74ee6ce3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('rut', sa.String(), nullable=True))
    op.add_column('clientes', sa.Column('razon_social', sa.String(), nullable=True))
    op.add_column('clientes', sa.Column('giro', sa.String(), nullable=True))
    op.add_column('clientes', sa.Column('es_empresa', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_clientes_rut'), 'clientes', ['rut'], unique=False)
    op.add_column('pedidos', sa.Column('tipo_documento_tributario_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pedidos', 'tipos_documento_tributario', ['tipo_documento_tributario_id'], ['id'], ondelete='RESTRICT')
    op.add_column('tipos_documento_tributario', sa.Column('descripcion', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tipos_documento_tributario', 'descripcion')
    op.drop_constraint(None, 'pedidos', type_='foreignkey')
    op.drop_column('pedidos', 'tipo_documento_tributario_id')
    op.drop_index(op.f('ix_clientes_rut'), table_name='clientes')
    op.drop_column('clientes', 'es_empresa')
    op.drop_column('clientes', 'giro')
    op.drop_column('clientes', 'razon_social')
    op.drop_column('clientes', 'rut')
    # ### end Alembic commands ###
