"""add_stock_minimo_y_critico_to_productos

Revision ID: 5938840ce1ec
Revises: 676e87eaf6d1
Create Date: 2025-12-16 14:14:30.656942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5938840ce1ec'
down_revision: Union[str, None] = '676e87eaf6d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('stock_minimo', sa.Integer(), nullable=True))
    op.add_column('productos', sa.Column('stock_critico', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productos', 'stock_critico')
    op.drop_column('productos', 'stock_minimo')
    # ### end Alembic commands ###
