"""add_peso_bruto_kg_to_lotes

Revision ID: 5a8d8b2cf3b3
Revises: f4503dd6bdfa
Create Date: 2026-03-09 20:14:09.990947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a8d8b2cf3b3'
down_revision: Union[str, None] = 'f4503dd6bdfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lotes', sa.Column('peso_bruto_kg', sa.Numeric(precision=8, scale=3), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lotes', 'peso_bruto_kg')
    # ### end Alembic commands ###
