"""agregar_medios_pago_estados_cheque

Revision ID: 5d69193ba885
Revises: a6f7dbe92e02
Create Date: 2025-12-31 13:33:44.866118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d69193ba885'
down_revision: Union[str, None] = 'a6f7dbe92e02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estados_cheque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('es_final', sa.Boolean(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estados_cheque_codigo'), 'estados_cheque', ['codigo'], unique=True)
    op.create_index(op.f('ix_estados_cheque_id'), 'estados_cheque', ['id'], unique=False)
    op.create_table('medios_pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('permite_cheque', sa.Boolean(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medios_pago_codigo'), 'medios_pago', ['codigo'], unique=True)
    op.create_index(op.f('ix_medios_pago_id'), 'medios_pago', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medios_pago_id'), table_name='medios_pago')
    op.drop_index(op.f('ix_medios_pago_codigo'), table_name='medios_pago')
    op.drop_table('medios_pago')
    op.drop_index(op.f('ix_estados_cheque_id'), table_name='estados_cheque')
    op.drop_index(op.f('ix_estados_cheque_codigo'), table_name='estados_cheque')
    op.drop_table('estados_cheque')
    # ### end Alembic commands ###
