"""agregar_tabla_bancos

Revision ID: 5f16b24fa823
Revises: 014336a399a5
Create Date: 2025-12-31 16:28:59.557927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f16b24fa823'
down_revision: Union[str, None] = '014336a399a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Crear tabla bancos
    op.create_table('bancos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('nombre_corto', sa.String(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bancos_codigo'), 'bancos', ['codigo'], unique=True)
    op.create_index(op.f('ix_bancos_id'), 'bancos', ['id'], unique=False)
    
    # 2. Insertar banco por defecto
    from sqlalchemy.sql import table, column
    from sqlalchemy import String, Integer, Boolean
    
    bancos_table = table('bancos',
        column('id', Integer),
        column('codigo', String),
        column('nombre', String),
        column('nombre_corto', String),
        column('activo', Boolean)
    )
    
    op.bulk_insert(bancos_table, [
        {'id': 1, 'codigo': 'GENERICO', 'nombre': 'Banco Genérico', 'nombre_corto': 'Genérico', 'activo': True}
    ])
    
    # 3. Agregar columna banco_id como nullable primero
    op.add_column('cheques', sa.Column('banco_id', sa.Integer(), nullable=True))
    
    # 4. Actualizar registros existentes con banco por defecto
    cheques_table = table('cheques',
        column('banco_id', Integer),
        column('banco', String)
    )
    
    op.execute(
        cheques_table.update().values(banco_id=1)
    )
    
    # 5. Hacer la columna NOT NULL ahora que todos los registros tienen valor
    op.alter_column('cheques', 'banco_id', nullable=False)
    
    # 6. Crear foreign key
    op.create_foreign_key(None, 'cheques', 'bancos', ['banco_id'], ['id'], ondelete='RESTRICT')
    
    # 7. Eliminar columna banco antigua
    op.drop_column('cheques', 'banco')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cheques', sa.Column('banco', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'cheques', type_='foreignkey')
    op.drop_column('cheques', 'banco_id')
    op.drop_index(op.f('ix_bancos_id'), table_name='bancos')
    op.drop_index(op.f('ix_bancos_codigo'), table_name='bancos')
    op.drop_table('bancos')
    # ### end Alembic commands ###
