"""add_notifications_table

Revision ID: 5f21c9c60706
Revises: a1b2c3d4e5f6
Create Date: 2026-03-26 12:58:31.770704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5f21c9c60706'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('action_url', sa.String(length=500), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_tenant_id'), 'notifications', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.alter_column('configuracion_landing', 'max_km_delivery',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               comment=None,
               existing_comment='Distancia máxima en kilómetros para aceptar pedidos con delivery. NULL = sin límite.',
               existing_nullable=True)
    op.alter_column('users', 'is_superadmin',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Super administrador de la plataforma. Tiene acceso cross-tenant.',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_superadmin',
               existing_type=sa.BOOLEAN(),
               comment='Super administrador de la plataforma. Tiene acceso cross-tenant.',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('configuracion_landing', 'max_km_delivery',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               comment='Distancia máxima en kilómetros para aceptar pedidos con delivery. NULL = sin límite.',
               existing_nullable=True)
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_tenant_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
