"""add_entrega_inmediata_to_canales_venta

Revision ID: 621ed46446aa
Revises: 38d371de575b
Create Date: 2026-03-25 12:01:58.672425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '621ed46446aa'
down_revision: Union[str, None] = '38d371de575b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('canales_venta', sa.Column('entrega_inmediata', sa.Boolean(), nullable=False, server_default='false'))
    op.execute("UPDATE canales_venta SET entrega_inmediata = true WHERE codigo = 'POS'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('canales_venta', 'entrega_inmediata')
    # ### end Alembic commands ###
