"""add_tipo_documento_table_and_update_compras

Revision ID: 676e87eaf6d1
Revises: 94aee9219b27
Create Date: 2025-12-16 14:01:35.385618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '676e87eaf6d1'
down_revision: Union[str, None] = '94aee9219b27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipos_documento_tributario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipos_documento_tributario_codigo'), 'tipos_documento_tributario', ['codigo'], unique=True)
    op.create_index(op.f('ix_tipos_documento_tributario_id'), 'tipos_documento_tributario', ['id'], unique=False)

    # Insert default Type to ensure consistency for existing records
    op.execute("INSERT INTO tipos_documento_tributario (codigo, nombre, activo) VALUES ('FAC', 'Factura Electrónica', true)")
    
    # Get the ID of the inserted row (assuming it is 1, but safer to just use literal 1 if sequence started)
    # Since we just created the table, ID likely 1.
    
    op.add_column('compras', sa.Column('tipo_documento_id', sa.Integer(), nullable=False, server_default='1'))
    op.alter_column('compras', 'tipo_documento_id', server_default=None) # Remove default
    
    op.create_foreign_key(None, 'compras', 'tipos_documento_tributario', ['tipo_documento_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('compras', 'tipo_documento')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('compras', sa.Column('tipo_documento', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'compras', type_='foreignkey')
    op.drop_column('compras', 'tipo_documento_id')
    op.drop_index(op.f('ix_tipos_documento_tributario_id'), table_name='tipos_documento_tributario')
    op.drop_index(op.f('ix_tipos_documento_tributario_codigo'), table_name='tipos_documento_tributario')
    op.drop_table('tipos_documento_tributario')
    # ### end Alembic commands ###
