"""add_numero_pedido_to_pedidos

Revision ID: 6782251ed843
Revises: 51165dcf3d23
Create Date: 2026-02-17 17:24:59.949736

"""
from typing import Sequence, Union
from datetime import datetime

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision: str = '6782251ed843'
down_revision: Union[str, None] = '51165dcf3d23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Agregar columna numero_pedido como nullable temporalmente
    op.add_column('pedidos', sa.Column('numero_pedido', sa.String(length=50), nullable=True))
    
    # 2. Generar numero_pedido para los pedidos existentes
    connection = op.get_bind()
    
    # Obtener año actual
    year = datetime.now().year
    
    # Obtener todos los tenants
    tenants = connection.execute(text("SELECT id, codigo FROM tenants ORDER BY id")).fetchall()
    
    for tenant_row in tenants:
        tenant_id = tenant_row[0]
        codigo_tenant = tenant_row[1]
        
        # Usar el codigo completo en uppercase (garantiza unicidad ya que codigo es UNIQUE en tenants)
        prefijo = codigo_tenant.upper()
        
        # Obtener pedidos de este tenant ordenados por fecha
        pedidos = connection.execute(text("""
            SELECT p.id 
            FROM pedidos p
            JOIN clientes c ON p.cliente_id = c.id
            WHERE c.tenant_id = :tenant_id
            ORDER BY p.fecha_pedido ASC, p.id ASC
        """), {"tenant_id": tenant_id}).fetchall()
        
        # Generar numero_pedido para cada pedido
        for idx, pedido_row in enumerate(pedidos, start=1):
            pedido_id = pedido_row[0]
            numero_pedido = f"{prefijo}-{year}-{idx:05d}"
            
            connection.execute(text("""
                UPDATE pedidos 
                SET numero_pedido = :numero_pedido 
                WHERE id = :pedido_id
            """), {"numero_pedido": numero_pedido, "pedido_id": pedido_id})
        
        # Actualizar el correlativo del tenant
        connection.execute(text("""
            UPDATE tenants 
            SET correlativo_pedido = :correlativo 
            WHERE id = :tenant_id
        """), {"correlativo": len(pedidos), "tenant_id": tenant_id})
    
    # 3. Hacer la columna NOT NULL y agregar índice único
    op.alter_column('pedidos', 'numero_pedido', nullable=False)
    op.create_index(op.f('ix_pedidos_numero_pedido'), 'pedidos', ['numero_pedido'], unique=True)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pedidos_numero_pedido'), table_name='pedidos')
    op.drop_column('pedidos', 'numero_pedido')
    # ### end Alembic commands ###
