"""agregar_paleta_id_a_configuracion_landing

Revision ID: 67ab83dc5f10
Revises: ff911497bb86
Create Date: 2026-02-24 02:27:27.247721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67ab83dc5f10'
down_revision: Union[str, None] = 'ff911497bb86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # SOLO agregar campo paleta_id a configuracion_landing
    op.add_column('configuracion_landing', sa.Column('paleta_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_configuracion_landing_paleta', 'configuracion_landing', 'paleta_colores', ['paleta_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_configuracion_landing_paleta', 'configuracion_landing', type_='foreignkey')
    op.drop_column('configuracion_landing', 'paleta_id')
    # ### end Alembic commands ###
