"""add_estados_pedido_table_and_change_pedido_estado_to_fk

Revision ID: 6d5e03d2ec23
Revises: 2f1684fb9ca7
Create Date: 2026-02-17 23:59:29.209527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d5e03d2ec23'
down_revision: Union[str, None] = '2f1684fb9ca7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # PASO 1: Crear tabla estados_pedido
    op.create_table('estados_pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('es_final', sa.Boolean(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estados_pedido_codigo'), 'estados_pedido', ['codigo'], unique=True)
    op.create_index(op.f('ix_estados_pedido_id'), 'estados_pedido', ['id'], unique=False)
    
    # PASO 2: Insertar estados iniciales (seed inline)
    op.execute("""
        INSERT INTO estados_pedido (id, codigo, nombre, descripcion, color, orden, es_final, activo) VALUES
        (1, 'PENDIENTE', 'Pendiente', 'Pedido creado, esperando confirmación', 'yellow-500', 1, false, true),
        (2, 'CONFIRMADO', 'Confirmado', 'Pedido confirmado, inventario descontado', 'blue-500', 2, false, true),
        (3, 'EN_PREPARACION', 'En Preparación', 'Pedido en proceso de preparación', 'purple-500', 3, false, true),
        (4, 'ENTREGADO', 'Entregado', 'Pedido entregado al cliente', 'green-500', 4, true, true),
        (5, 'CANCELADO', 'Cancelado', 'Pedido cancelado, inventario devuelto', 'red-500', 5, true, true)
        ON CONFLICT DO NOTHING;
    """)
    
    # PASO 3: Agregar columna estado_id como NULLABLE temporalmente
    op.add_column('pedidos', sa.Column('estado_id', sa.Integer(), nullable=True))
    
    # PASO 4: Migrar datos existentes de String a FK
    op.execute("""
        UPDATE pedidos 
        SET estado_id = CASE estado
            WHEN 'PENDIENTE' THEN 1
            WHEN 'CONFIRMADO' THEN 2
            WHEN 'EN_PREPARACION' THEN 3
            WHEN 'ENTREGADO' THEN 4
            WHEN 'CANCELADO' THEN 5
            ELSE 1  -- Default a PENDIENTE si hay algún valor inesperado
        END
        WHERE estado_id IS NULL;
    """)
    
    # PASO 5: Hacer estado_id NOT NULL ahora que todos tienen valor
    op.alter_column('pedidos', 'estado_id', nullable=False)
    
    # PASO 6: Crear FK constraint
    op.create_foreign_key('fk_pedidos_estado_id', 'pedidos', 'estados_pedido', ['estado_id'], ['id'], ondelete='RESTRICT')
    
    # PASO 7: Eliminar columna antigua
    op.drop_column('pedidos', 'estado')
    
    # COMENTADO: Cambios no relacionados que causan problemas con multi-tenant
    # op.drop_index('ix_clientes_tenant_email_unique', table_name='clientes', postgresql_where='(email IS NOT NULL)')
    # op.create_unique_constraint(None, 'clientes', ['email'])
    # op.drop_index('ix_locales_tenant_codigo_unique', table_name='locales')
    # op.drop_index('ix_locales_tenant_nombre_unique', table_name='locales')
    # op.drop_index('ix_locales_codigo', table_name='locales')
    # op.create_index(op.f('ix_locales_codigo'), 'locales', ['codigo'], unique=True)
    # op.drop_index('ix_locales_nombre', table_name='locales')
    # op.create_index(op.f('ix_locales_nombre'), 'locales', ['nombre'], unique=True)
    # op.drop_index('ix_productos_tenant_sku_unique', table_name='productos')
    # op.drop_index('ix_productos_sku', table_name='productos')
    # op.create_index(op.f('ix_productos_sku'), 'productos', ['sku'], unique=True)
    # op.create_index(op.f('ix_proveedores_tenant_id'), 'proveedores', ['tenant_id'], unique=False)
    # op.drop_constraint('fk_proveedores_tenant', 'proveedores', type_='foreignkey')
    # op.create_foreign_key(None, 'proveedores', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # COMENTADO: Cambios no relacionados
    # op.drop_constraint(None, 'proveedores', type_='foreignkey')
    # op.create_foreign_key('fk_proveedores_tenant', 'proveedores', 'tenants', ['tenant_id'], ['id'])
    # op.drop_index(op.f('ix_proveedores_tenant_id'), table_name='proveedores')
    # op.drop_index(op.f('ix_productos_sku'), table_name='productos')
    # op.create_index('ix_productos_sku', 'productos', ['sku'], unique=False)
    # op.create_index('ix_productos_tenant_sku_unique', 'productos', ['tenant_id', 'sku'], unique=False)
    
    # PASO 1: Agregar columna estado (String) como NULLABLE temporalmente
    op.add_column('pedidos', sa.Column('estado', sa.VARCHAR(), autoincrement=False, nullable=True))
    
    # PASO 2: Migrar datos de vuelta de FK a String
    op.execute("""
        UPDATE pedidos
        SET estado = (
            SELECT codigo 
            FROM estados_pedido 
            WHERE estados_pedido.id = pedidos.estado_id
        )
        WHERE estado IS NULL;
    """)
    
    # PASO 3: Hacer estado NOT NULL
    op.alter_column('pedidos', 'estado', nullable=False)
    
    # PASO 4: Eliminar FK y columna estado_id
    op.drop_constraint('fk_pedidos_estado_id', 'pedidos', type_='foreignkey')
    op.drop_column('pedidos', 'estado_id')
    
    # PASO 5: Eliminar tabla estados_pedido
    op.drop_index(op.f('ix_estados_pedido_id'), table_name='estados_pedido')
    op.drop_index(op.f('ix_estados_pedido_codigo'), table_name='estados_pedido')
    op.drop_table('estados_pedido')
    
    # COMENTADO: Revertir índices de locales y clientes
    # op.drop_index(op.f('ix_locales_nombre'), table_name='locales')
    # op.create_index('ix_locales_nombre', 'locales', ['nombre'], unique=False)
    # op.drop_index(op.f('ix_locales_codigo'), table_name='locales')
    # op.create_index('ix_locales_codigo', 'locales', ['codigo'], unique=False)
    # op.create_index('ix_locales_tenant_nombre_unique', 'locales', ['tenant_id', 'nombre'], unique=False)
    # op.create_index('ix_locales_tenant_codigo_unique', 'locales', ['tenant_id', 'codigo'], unique=False)
    # op.drop_constraint(None, 'clientes', type_='unique')
    # op.create_index('ix_clientes_tenant_email_unique', 'clientes', ['tenant_id', 'email'], unique=False, postgresql_where='(email IS NOT NULL)')
    # ### end Alembic commands ###
