"""Agregar tabla TipoVenta y relacion con CategoriaProducto

Revision ID: 6f75a40772fc
Revises: fd6f9456eefc
Create Date: 2026-01-05 13:14:51.445103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f75a40772fc'
down_revision: Union[str, None] = 'fd6f9456eefc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipos_venta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipos_venta_codigo'), 'tipos_venta', ['codigo'], unique=True)
    op.create_index(op.f('ix_tipos_venta_id'), 'tipos_venta', ['id'], unique=False)
    op.add_column('categorias_producto', sa.Column('tipo_venta_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'categorias_producto', 'tipos_venta', ['tipo_venta_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categorias_producto', type_='foreignkey')
    op.drop_column('categorias_producto', 'tipo_venta_id')
    op.drop_index(op.f('ix_tipos_venta_id'), table_name='tipos_venta')
    op.drop_index(op.f('ix_tipos_venta_codigo'), table_name='tipos_venta')
    op.drop_table('tipos_venta')
    # ### end Alembic commands ###
