"""fix_tipo_cobro_chofer_length

Revision ID: 70aa91428e1f
Revises: ca3354c36052
Create Date: 2026-03-16 20:54:57.637531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70aa91428e1f'
down_revision: Union[str, None] = 'ca3354c36052'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hojas_ruta', 'tipo_cobro_chofer',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.String(length=10),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hojas_ruta', 'tipo_cobro_chofer',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=5),
               existing_nullable=True)
    # ### end Alembic commands ###
