"""add_local_despacho_and_inventario_flag

Revision ID: 787f179b0bed
Revises: 78d3e9622bf7
Create Date: 2025-11-24 16:24:24.125466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '787f179b0bed'
down_revision: Union[str, None] = '78d3e9622bf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedidos', sa.Column('local_despacho_id', sa.Integer(), nullable=True))
    op.add_column('pedidos', sa.Column('inventario_descontado', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'pedidos', 'locales', ['local_despacho_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pedidos', type_='foreignkey')
    op.drop_column('pedidos', 'inventario_descontado')
    op.drop_column('pedidos', 'local_despacho_id')
    # ### end Alembic commands ###
