"""add_customer_address_and_order_notes

Revision ID: 78d3e9622bf7
Revises: 9e72c2b2d9d3
Create Date: 2025-11-24 15:57:16.258204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78d3e9622bf7'
down_revision: Union[str, None] = '9e72c2b2d9d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('direccion', sa.String(), nullable=True))
    op.add_column('clientes', sa.Column('comuna', sa.String(), nullable=True))
    op.add_column('pedidos', sa.Column('notas', sa.String(), nullable=True))
    op.add_column('pedidos', sa.Column('notas_admin', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pedidos', 'notas_admin')
    op.drop_column('pedidos', 'notas')
    op.drop_column('clientes', 'comuna')
    op.drop_column('clientes', 'direccion')
    # ### end Alembic commands ###
