"""add_comisiones_tables_and_porcentaje_comision_user

Revision ID: 79f6c6112c15
Revises: a3f791b2c4d8
Create Date: 2026-03-12 13:31:14.921652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79f6c6112c15'
down_revision: Union[str, None] = 'a3f791b2c4d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('liquidaciones_comisiones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('vendedor_id', sa.Integer(), nullable=False),
    sa.Column('periodo', sa.String(length=7), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('fecha_pago_prevista', sa.Date(), nullable=False),
    sa.Column('total_ventas_neto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_comision', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cantidad_pedidos', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_pago_real', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendedor_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'vendedor_id', 'periodo', name='uq_liquidacion_vendedor_periodo')
    )
    op.create_index(op.f('ix_liquidaciones_comisiones_id'), 'liquidaciones_comisiones', ['id'], unique=False)
    op.create_index(op.f('ix_liquidaciones_comisiones_periodo'), 'liquidaciones_comisiones', ['periodo'], unique=False)
    op.create_index(op.f('ix_liquidaciones_comisiones_tenant_id'), 'liquidaciones_comisiones', ['tenant_id'], unique=False)
    op.create_table('comisiones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('vendedor_id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('liquidacion_id', sa.Integer(), nullable=True),
    sa.Column('numero_pedido', sa.String(length=50), nullable=False),
    sa.Column('porcentaje', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('monto_bruto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('monto_neto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('monto_comision', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('periodo', sa.String(length=7), nullable=False),
    sa.Column('fecha_pedido', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_generacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['liquidacion_id'], ['liquidaciones_comisiones.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendedor_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pedido_id')
    )
    op.create_index(op.f('ix_comisiones_id'), 'comisiones', ['id'], unique=False)
    op.create_index(op.f('ix_comisiones_periodo'), 'comisiones', ['periodo'], unique=False)
    op.create_index(op.f('ix_comisiones_tenant_id'), 'comisiones', ['tenant_id'], unique=False)
    op.add_column('users', sa.Column('porcentaje_comision', sa.Numeric(precision=5, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'porcentaje_comision')
    op.drop_index(op.f('ix_comisiones_tenant_id'), table_name='comisiones')
    op.drop_index(op.f('ix_comisiones_periodo'), table_name='comisiones')
    op.drop_index(op.f('ix_comisiones_id'), table_name='comisiones')
    op.drop_table('comisiones')
    op.drop_index(op.f('ix_liquidaciones_comisiones_tenant_id'), table_name='liquidaciones_comisiones')
    op.drop_index(op.f('ix_liquidaciones_comisiones_periodo'), table_name='liquidaciones_comisiones')
    op.drop_index(op.f('ix_liquidaciones_comisiones_id'), table_name='liquidaciones_comisiones')
    op.drop_table('liquidaciones_comisiones')
    # ### end Alembic commands ###
