"""Add sistema despachos - tablas despachos y picking_items

Revision ID: 7b5f16d5669d
Revises: a3d2f8cc6f2d
Create Date: 2026-01-07 21:37:12.631380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b5f16d5669d'
down_revision: Union[str, None] = 'a3d2f8cc6f2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('despachos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('despachador_user_id', sa.Integer(), nullable=False),
    sa.Column('estado_despacho', sa.Enum('ASIGNADO', 'EN_PICKING', 'LISTO_EMPAQUE', 'EN_RUTA', 'ENTREGADO', 'CANCELADO', name='estadodespacho'), nullable=False),
    sa.Column('fecha_asignacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_inicio_picking', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_fin_picking', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_inicio_ruta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_entrega', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notas_despacho', sa.Text(), nullable=True),
    sa.Column('ubicacion_actual', sa.String(), nullable=True),
    sa.Column('hora_estimada_entrega', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['despachador_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pedido_id')
    )
    op.create_index(op.f('ix_despachos_id'), 'despachos', ['id'], unique=False)
    op.create_table('picking_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('despacho_id', sa.Integer(), nullable=False),
    sa.Column('item_pedido_id', sa.Integer(), nullable=False),
    sa.Column('usuario_picking_id', sa.Integer(), nullable=True),
    sa.Column('cantidad_solicitada', sa.Integer(), nullable=True),
    sa.Column('cantidad_pickeada', sa.Integer(), nullable=True),
    sa.Column('lote_codigo', sa.String(), nullable=True),
    sa.Column('peso_solicitado', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('peso_real', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('fecha_vencimiento', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ubicacion_picking', sa.String(), nullable=True),
    sa.Column('codigo_barras_escaneado', sa.String(), nullable=True),
    sa.Column('fecha_picking', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notas_picking', sa.Text(), nullable=True),
    sa.Column('completado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['despacho_id'], ['despachos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_pedido_id'], ['items_pedido.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_picking_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_picking_items_despacho', 'picking_items', ['despacho_id'], unique=False)
    op.create_index(op.f('ix_picking_items_id'), 'picking_items', ['id'], unique=False)
    op.create_index('ix_picking_items_item_pedido', 'picking_items', ['item_pedido_id'], unique=False)
    op.create_index('ix_picking_items_lote', 'picking_items', ['lote_codigo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_picking_items_lote', table_name='picking_items')
    op.drop_index('ix_picking_items_item_pedido', table_name='picking_items')
    op.drop_index(op.f('ix_picking_items_id'), table_name='picking_items')
    op.drop_index('ix_picking_items_despacho', table_name='picking_items')
    op.drop_table('picking_items')
    op.drop_index(op.f('ix_despachos_id'), table_name='despachos')
    op.drop_table('despachos')
    # ### end Alembic commands ###
