"""Tablas stock_cajas_proveedor y movimientos_stock_cajas

Revision ID: 7ce7243d1bbd
Revises: b5127814e78c
Create Date: 2026-01-06 16:02:48.937095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ce7243d1bbd'
down_revision: Union[str, None] = 'b5127814e78c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_cajas_proveedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('cajas_disponibles', sa.Integer(), nullable=False),
    sa.Column('cajas_totales_recibidas', sa.Integer(), nullable=False),
    sa.Column('cajas_totales_vendidas', sa.Integer(), nullable=False),
    sa.Column('fecha_ultima_actualizacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('producto_id', 'proveedor_id', name='uix_stock_cajas_producto_proveedor')
    )
    op.create_index(op.f('ix_stock_cajas_proveedor_id'), 'stock_cajas_proveedor', ['id'], unique=False)
    op.create_table('movimientos_stock_cajas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=True),
    sa.Column('enrolamiento_id', sa.Integer(), nullable=True),
    sa.Column('pedido_id', sa.Integer(), nullable=True),
    sa.Column('tipo_movimiento', sa.String(), nullable=False),
    sa.Column('cajas_movimiento', sa.Integer(), nullable=False),
    sa.Column('cajas_antes', sa.Integer(), nullable=False),
    sa.Column('cajas_despues', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('usuario', sa.String(), nullable=True),
    sa.Column('fecha_movimiento', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['enrolamiento_id'], ['enrolamientos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_movimientos_stock_cajas_fecha', 'movimientos_stock_cajas', ['fecha_movimiento'], unique=False)
    op.create_index(op.f('ix_movimientos_stock_cajas_fecha_movimiento'), 'movimientos_stock_cajas', ['fecha_movimiento'], unique=False)
    op.create_index(op.f('ix_movimientos_stock_cajas_id'), 'movimientos_stock_cajas', ['id'], unique=False)
    op.create_index('ix_movimientos_stock_cajas_producto_proveedor', 'movimientos_stock_cajas', ['producto_id', 'proveedor_id'], unique=False)
    op.create_index('ix_movimientos_stock_cajas_tipo', 'movimientos_stock_cajas', ['tipo_movimiento'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_movimientos_stock_cajas_tipo', table_name='movimientos_stock_cajas')
    op.drop_index('ix_movimientos_stock_cajas_producto_proveedor', table_name='movimientos_stock_cajas')
    op.drop_index(op.f('ix_movimientos_stock_cajas_id'), table_name='movimientos_stock_cajas')
    op.drop_index(op.f('ix_movimientos_stock_cajas_fecha_movimiento'), table_name='movimientos_stock_cajas')
    op.drop_index('ix_movimientos_stock_cajas_fecha', table_name='movimientos_stock_cajas')
    op.drop_table('movimientos_stock_cajas')
    op.drop_index(op.f('ix_stock_cajas_proveedor_id'), table_name='stock_cajas_proveedor')
    op.drop_table('stock_cajas_proveedor')
    # ### end Alembic commands ###
