"""add unidad_medida_id to precios table

Revision ID: 82a9a74af741
Revises: 1ac336967d21
Create Date: 2026-02-15 00:53:16.308677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82a9a74af741'
down_revision: Union[str, None] = '1ac336967d21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Agregar columna unidad_medida_id primero como nullable
    op.add_column('precios', sa.Column('unidad_medida_id', sa.Integer(), nullable=True))
    
    # Asignar una unidad por defecto a registros existentes (asumiendo id=1 es la unidad base)
    # Esto asume que existe una unidad con id=1 en la tabla unidades_medida
    op.execute("UPDATE precios SET unidad_medida_id = 1 WHERE unidad_medida_id IS NULL")
    
    # Ahora hacer la columna NOT NULL
    op.alter_column('precios', 'unidad_medida_id', nullable=False)
    
    # Eliminar constraint antigua y crear nueva con unidad_medida_id
    op.drop_constraint('uix_precio_producto_local', 'precios', type_='unique')
    op.create_unique_constraint('uix_precio_producto_local_unidad', 'precios', ['producto_id', 'local_id', 'unidad_medida_id'])
    op.create_foreign_key(None, 'precios', 'unidades_medida', ['unidad_medida_id'], ['id'], ondelete='RESTRICT')
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'precios', type_='foreignkey')
    op.drop_constraint('uix_precio_producto_local_unidad', 'precios', type_='unique')
    op.create_unique_constraint('uix_precio_producto_local', 'precios', ['producto_id', 'local_id'])
    op.drop_column('precios', 'unidad_medida_id')
    # ### end Alembic commands ###
