"""add_notas_credito_table

Revision ID: 88cbf2da3ffb
Revises: d2e3f4a5b6c7
Create Date: 2026-03-24 20:05:27.006331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88cbf2da3ffb'
down_revision: Union[str, None] = 'd2e3f4a5b6c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notas_credito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('tipo_documento_id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('folio_sii', sa.String(), nullable=True),
    sa.Column('fecha_emision', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('estado_sii', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tipo_documento_id'], ['tipos_documento_tributario.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notas_credito_folio_sii'), 'notas_credito', ['folio_sii'], unique=False)
    op.create_index(op.f('ix_notas_credito_id'), 'notas_credito', ['id'], unique=False)
    op.create_index(op.f('ix_notas_credito_pedido_id'), 'notas_credito', ['pedido_id'], unique=True)
    op.create_index(op.f('ix_notas_credito_tenant_id'), 'notas_credito', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notas_credito_tenant_id'), table_name='notas_credito')
    op.drop_index(op.f('ix_notas_credito_pedido_id'), table_name='notas_credito')
    op.drop_index(op.f('ix_notas_credito_id'), table_name='notas_credito')
    op.drop_index(op.f('ix_notas_credito_folio_sii'), table_name='notas_credito')
    op.drop_table('notas_credito')
    # ### end Alembic commands ###
