"""add_proveedor_to_items_pedido_and_asignaciones_picking

Revision ID: 8a4a7e908f22
Revises: a1f3c2d4e5b6
Create Date: 2026-03-06 20:15:02.515386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a4a7e908f22'
down_revision: Union[str, None] = 'a1f3c2d4e5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asignaciones_picking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=False),
    sa.Column('item_pedido_id', sa.Integer(), nullable=False),
    sa.Column('peso_real', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('precio_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('monto_real', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_asignacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_pedido_id'], ['items_pedido.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lote_id')
    )
    op.create_index(op.f('ix_asignaciones_picking_id'), 'asignaciones_picking', ['id'], unique=False)
    op.create_index('ix_asignaciones_picking_item', 'asignaciones_picking', ['item_pedido_id'], unique=False)
    op.create_index('ix_asignaciones_picking_lote', 'asignaciones_picking', ['lote_id'], unique=False)
    op.add_column('items_pedido', sa.Column('proveedor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'items_pedido', 'proveedores', ['proveedor_id'], ['id'], ondelete='RESTRICT')
    # Insert PREVENTA estado if not exists
    op.execute("SELECT setval('estados_pedido_id_seq', COALESCE((SELECT MAX(id) FROM estados_pedido), 0), true)")
    op.execute("""
        INSERT INTO estados_pedido (codigo, nombre, descripcion, color, orden, es_final, activo)
        SELECT 'PREVENTA', 'Pre-Venta', 'Pedido de pre-venta pendiente de picking en anden', 'purple-500', 0, false, true
        WHERE NOT EXISTS (SELECT 1 FROM estados_pedido WHERE codigo = 'PREVENTA')
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'items_pedido', type_='foreignkey')
    op.drop_column('items_pedido', 'proveedor_id')
    op.drop_index('ix_asignaciones_picking_lote', table_name='asignaciones_picking')
    op.drop_index('ix_asignaciones_picking_item', table_name='asignaciones_picking')
    op.drop_index(op.f('ix_asignaciones_picking_id'), table_name='asignaciones_picking')
    op.drop_table('asignaciones_picking')
    # ### end Alembic commands ###
