"""add recibido a solicitud

Revision ID: 8c8efa23f3b8
Revises: f034a5f09e4c
Create Date: 2026-03-02 23:32:22.389988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c8efa23f3b8'
down_revision: Union[str, None] = 'f034a5f09e4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Agregar recibido como nullable y default False
    op.add_column('solicitudes_transferencia', sa.Column('recibido', sa.Boolean(), nullable=True, server_default=sa.false()))
    op.add_column('solicitudes_transferencia', sa.Column('usuario_receptor_id', sa.Integer(), nullable=True))
    op.add_column('solicitudes_transferencia', sa.Column('fecha_recepcion', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'solicitudes_transferencia', 'users', ['usuario_receptor_id'], ['id'], ondelete='RESTRICT')
    # 2. Actualizar registros existentes a False
    op.execute("UPDATE solicitudes_transferencia SET recibido = FALSE WHERE recibido IS NULL;")
    # 3. Alterar columna a NOT NULL
    op.alter_column('solicitudes_transferencia', 'recibido', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'solicitudes_transferencia', type_='foreignkey')
    op.drop_column('solicitudes_transferencia', 'fecha_recepcion')
    op.drop_column('solicitudes_transferencia', 'usuario_receptor_id')
    op.drop_column('solicitudes_transferencia', 'recibido')
    # ### end Alembic commands ###
