"""add_precio_incluye_iva_to_productos

Revision ID: 8cf98e32f680
Revises: b9e394a58418
Create Date: 2026-03-07 01:46:34.376160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cf98e32f680'
down_revision: Union[str, None] = 'b9e394a58418'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('precio_incluye_iva', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productos', 'precio_incluye_iva')
    # ### end Alembic commands ###
