"""add_compras_proveedores

Revision ID: 94aee9219b27
Revises: d4a428b8aba2
Create Date: 2025-12-16 16:00:30.969966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94aee9219b27'
down_revision: Union[str, None] = 'd4a428b8aba2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proveedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('rut', sa.String(), nullable=True),
    sa.Column('contacto', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('direccion', sa.String(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proveedores_id'), 'proveedores', ['id'], unique=False)
    op.create_index(op.f('ix_proveedores_nombre'), 'proveedores', ['nombre'], unique=False)
    op.create_index(op.f('ix_proveedores_rut'), 'proveedores', ['rut'], unique=True)
    op.create_table('compras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('local_id', sa.Integer(), nullable=False),
    sa.Column('fecha_compra', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('numero_documento', sa.String(), nullable=True),
    sa.Column('tipo_documento', sa.String(), nullable=True),
    sa.Column('monto_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['local_id'], ['locales.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compras_id'), 'compras', ['id'], unique=False)
    op.create_table('detalles_compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('compra_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['compra_id'], ['compras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detalles_compra_id'), 'detalles_compra', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detalles_compra_id'), table_name='detalles_compra')
    op.drop_table('detalles_compra')
    op.drop_index(op.f('ix_compras_id'), table_name='compras')
    op.drop_table('compras')
    op.drop_index(op.f('ix_proveedores_rut'), table_name='proveedores')
    op.drop_index(op.f('ix_proveedores_nombre'), table_name='proveedores')
    op.drop_index(op.f('ix_proveedores_id'), table_name='proveedores')
    op.drop_table('proveedores')
    # ### end Alembic commands ###
