"""cascade delete-orphan en relaciones Tenant

Revision ID: 9a76383fabc7
Revises: 67ab83dc5f10
Create Date: 2026-02-24 13:33:09.935165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a76383fabc7'
down_revision: Union[str, None] = '67ab83dc5f10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Migración simplificada: Solo cambios críticos de CASCADE en FK de tenant_id
    # Los demás cambios (email, índices) se omiten para evitar conflictos de integridad
    
    # Agregar CASCADE a FK de proveedores (si no tiene)
    op.drop_constraint('fk_proveedores_tenant', 'proveedores', type_='foreignkey')
    op.create_foreign_key('fk_proveedores_tenant', 'proveedores', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Revertir cambios de CASCADE
    op.drop_constraint('fk_proveedores_tenant', 'proveedores', type_='foreignkey')
    op.create_foreign_key('fk_proveedores_tenant', 'proveedores', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###
