"""Agregar TipoLocal y local_despacho_default

Revision ID: a3d2f8cc6f2d
Revises: bb6f46a4c026
Create Date: 2026-01-07 20:24:24.294009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3d2f8cc6f2d'
down_revision: Union[str, None] = 'bb6f46a4c026'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipos_local',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipos_local_codigo'), 'tipos_local', ['codigo'], unique=True)
    op.create_index(op.f('ix_tipos_local_id'), 'tipos_local', ['id'], unique=False)
    op.create_index(op.f('ix_tipos_local_nombre'), 'tipos_local', ['nombre'], unique=False)
    op.add_column('locales', sa.Column('tipo_local_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'locales', 'tipos_local', ['tipo_local_id'], ['id'], ondelete='SET NULL')
    op.add_column('tipos_pedido', sa.Column('local_despacho_default_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tipos_pedido', 'locales', ['local_despacho_default_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tipos_pedido', type_='foreignkey')
    op.drop_column('tipos_pedido', 'local_despacho_default_id')
    op.drop_constraint(None, 'locales', type_='foreignkey')
    op.drop_column('locales', 'tipo_local_id')
    op.drop_index(op.f('ix_tipos_local_nombre'), table_name='tipos_local')
    op.drop_index(op.f('ix_tipos_local_id'), table_name='tipos_local')
    op.drop_index(op.f('ix_tipos_local_codigo'), table_name='tipos_local')
    op.drop_table('tipos_local')
    # ### end Alembic commands ###
