"""add_plazo_dias_to_medios_pago_and_cobros_pendientes

Revision ID: a7933ae95522
Revises: 70aa91428e1f
Create Date: 2026-03-23 12:12:48.421108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7933ae95522'
down_revision: Union[str, None] = '70aa91428e1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cobros_pendientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_vencimiento', sa.DateTime(timezone=True), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('fecha_recepcion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cobros_pendientes_id'), 'cobros_pendientes', ['id'], unique=False)
    op.add_column('medios_pago', sa.Column('plazo_dias', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medios_pago', 'plazo_dias')
    op.drop_index(op.f('ix_cobros_pendientes_id'), table_name='cobros_pendientes')
    op.drop_table('cobros_pendientes')
    # ### end Alembic commands ###
