"""add_reservado_to_lotes

Revision ID: b2e04a4b810d
Revises: 8a4a7e908f22
Create Date: 2026-03-06 22:54:19.902201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2e04a4b810d'
down_revision: Union[str, None] = '8a4a7e908f22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
