"""Tabla precios_proveedor para cajas variables

Revision ID: b5127814e78c
Revises: 0cf23bf5f336
Create Date: 2026-01-06 13:05:56.816116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5127814e78c'
down_revision: Union[str, None] = '0cf23bf5f336'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('precios_proveedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('precio_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_vigencia', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('notas', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('producto_id', 'proveedor_id', name='uix_precio_producto_proveedor')
    )
    op.create_index(op.f('ix_precios_proveedor_id'), 'precios_proveedor', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_precios_proveedor_id'), table_name='precios_proveedor')
    op.drop_table('precios_proveedor')
    # ### end Alembic commands ###
