"""add_reservado_column_to_lotes

Revision ID: b9e394a58418
Revises: 284759954d70
Create Date: 2026-03-06 23:06:22.824274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9e394a58418'
down_revision: Union[str, None] = '284759954d70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lotes', sa.Column('reservado', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lotes', 'reservado')
    # ### end Alembic commands ###
