"""Fix stock cajas relationships

Revision ID: bb6f46a4c026
Revises: e05801cae0ac
Create Date: 2026-01-06 20:43:50.731865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb6f46a4c026'
down_revision: Union[str, None] = 'e05801cae0ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movimientos_stock_cajas', sa.Column('stock_cajas_id', sa.Integer(), nullable=True))
    op.add_column('movimientos_stock_cajas', sa.Column('peso_total_kg', sa.Float(), nullable=True))
    op.add_column('movimientos_stock_cajas', sa.Column('lote_codigo', sa.String(), nullable=True))
    op.add_column('movimientos_stock_cajas', sa.Column('referencia_tipo', sa.String(), nullable=True))
    op.add_column('movimientos_stock_cajas', sa.Column('referencia_id', sa.Integer(), nullable=True))
    op.add_column('movimientos_stock_cajas', sa.Column('notas', sa.Text(), nullable=True))
    op.create_index(op.f('ix_movimientos_stock_cajas_lote_codigo'), 'movimientos_stock_cajas', ['lote_codigo'], unique=False)
    op.create_index(op.f('ix_movimientos_stock_cajas_tipo_movimiento'), 'movimientos_stock_cajas', ['tipo_movimiento'], unique=False)
    op.create_foreign_key(None, 'movimientos_stock_cajas', 'stock_cajas_proveedor', ['stock_cajas_id'], ['id'], ondelete='CASCADE')
    op.add_column('stock_cajas_proveedor', sa.Column('peso_promedio_caja_kg', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_cajas_proveedor', 'peso_promedio_caja_kg')
    op.drop_constraint(None, 'movimientos_stock_cajas', type_='foreignkey')
    op.drop_index(op.f('ix_movimientos_stock_cajas_tipo_movimiento'), table_name='movimientos_stock_cajas')
    op.drop_index(op.f('ix_movimientos_stock_cajas_lote_codigo'), table_name='movimientos_stock_cajas')
    op.drop_column('movimientos_stock_cajas', 'notas')
    op.drop_column('movimientos_stock_cajas', 'referencia_id')
    op.drop_column('movimientos_stock_cajas', 'referencia_tipo')
    op.drop_column('movimientos_stock_cajas', 'lote_codigo')
    op.drop_column('movimientos_stock_cajas', 'peso_total_kg')
    op.drop_column('movimientos_stock_cajas', 'stock_cajas_id')
    # ### end Alembic commands ###
