"""agregar_sistema_caja_turnos_operaciones

Revision ID: becf5fa373d3
Revises: 38f1ff2192cd
Create Date: 2026-01-02 20:13:35.664120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'becf5fa373d3'
down_revision: Union[str, None] = '38f1ff2192cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('turnos_caja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendedor_id', sa.Integer(), nullable=False),
    sa.Column('local_id', sa.Integer(), nullable=False),
    sa.Column('fecha_apertura', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_cierre', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estado', sa.Enum('ABIERTO', 'CERRADO', name='estadoturnocaja'), nullable=False),
    sa.Column('monto_inicial', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('efectivo_esperado', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('efectivo_real', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('diferencia', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('observaciones_apertura', sa.Text(), nullable=True),
    sa.Column('observaciones_cierre', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['local_id'], ['locales.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vendedor_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_turno_vendedor_abierto', 'turnos_caja', ['vendedor_id', 'local_id', 'estado'], unique=False)
    op.create_index(op.f('ix_turnos_caja_estado'), 'turnos_caja', ['estado'], unique=False)
    op.create_index(op.f('ix_turnos_caja_fecha_apertura'), 'turnos_caja', ['fecha_apertura'], unique=False)
    op.create_index(op.f('ix_turnos_caja_fecha_cierre'), 'turnos_caja', ['fecha_cierre'], unique=False)
    op.create_index(op.f('ix_turnos_caja_id'), 'turnos_caja', ['id'], unique=False)
    op.create_table('operaciones_caja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turno_caja_id', sa.Integer(), nullable=False),
    sa.Column('tipo_operacion', sa.Enum('APERTURA', 'VENTA', 'INGRESO', 'EGRESO', 'DEVOLUCION', 'CIERRE', name='tipooperacioncaja'), nullable=False),
    sa.Column('fecha_operacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('pedido_id', sa.Integer(), nullable=True),
    sa.Column('medio_pago_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['medio_pago_id'], ['medios_pago.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['turno_caja_id'], ['turnos_caja.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operaciones_caja_fecha_operacion'), 'operaciones_caja', ['fecha_operacion'], unique=False)
    op.create_index(op.f('ix_operaciones_caja_id'), 'operaciones_caja', ['id'], unique=False)
    op.create_index(op.f('ix_operaciones_caja_tipo_operacion'), 'operaciones_caja', ['tipo_operacion'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operaciones_caja_tipo_operacion'), table_name='operaciones_caja')
    op.drop_index(op.f('ix_operaciones_caja_id'), table_name='operaciones_caja')
    op.drop_index(op.f('ix_operaciones_caja_fecha_operacion'), table_name='operaciones_caja')
    op.drop_table('operaciones_caja')
    op.drop_index(op.f('ix_turnos_caja_id'), table_name='turnos_caja')
    op.drop_index(op.f('ix_turnos_caja_fecha_cierre'), table_name='turnos_caja')
    op.drop_index(op.f('ix_turnos_caja_fecha_apertura'), table_name='turnos_caja')
    op.drop_index(op.f('ix_turnos_caja_estado'), table_name='turnos_caja')
    op.drop_index('idx_turno_vendedor_abierto', table_name='turnos_caja')
    op.drop_table('turnos_caja')
    # ### end Alembic commands ###
