"""Agregar campos de control SII para facturas

Revision ID: ca2653ba45bf
Revises: 55ae0810b1bc
Create Date: 2026-01-14 17:25:13.763048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca2653ba45bf'
down_revision: Union[str, None] = '55ae0810b1bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedidos', sa.Column('estado_sii', sa.String(), nullable=True))
    op.add_column('pedidos', sa.Column('folio_sii', sa.String(), nullable=True))
    op.add_column('pedidos', sa.Column('numero_dte', sa.String(), nullable=True))
    op.add_column('pedidos', sa.Column('fecha_envio_sii', sa.DateTime(timezone=True), nullable=True))
    op.add_column('pedidos', sa.Column('fecha_respuesta_sii', sa.DateTime(timezone=True), nullable=True))
    op.add_column('pedidos', sa.Column('xml_sii', sa.Text(), nullable=True))
    op.add_column('pedidos', sa.Column('respuesta_sii', sa.Text(), nullable=True))
    op.add_column('pedidos', sa.Column('observaciones_sii', sa.Text(), nullable=True))
    op.create_index(op.f('ix_pedidos_folio_sii'), 'pedidos', ['folio_sii'], unique=False)
    op.create_index(op.f('ix_pedidos_numero_dte'), 'pedidos', ['numero_dte'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pedidos_numero_dte'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_folio_sii'), table_name='pedidos')
    op.drop_column('pedidos', 'observaciones_sii')
    op.drop_column('pedidos', 'respuesta_sii')
    op.drop_column('pedidos', 'xml_sii')
    op.drop_column('pedidos', 'fecha_respuesta_sii')
    op.drop_column('pedidos', 'fecha_envio_sii')
    op.drop_column('pedidos', 'numero_dte')
    op.drop_column('pedidos', 'folio_sii')
    op.drop_column('pedidos', 'estado_sii')
    # ### end Alembic commands ###
