"""add_chofer_payment_fields_to_hojas_ruta

Revision ID: ca3354c36052
Revises: c3d1e8f2a7b9
Create Date: 2026-03-16 20:44:26.281683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca3354c36052'
down_revision: Union[str, None] = 'c3d1e8f2a7b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hojas_ruta', sa.Column('tipo_cobro_chofer', sa.String(length=5), nullable=True))
    op.add_column('hojas_ruta', sa.Column('tarifa_chofer', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('hojas_ruta', sa.Column('monto_cobro_chofer', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('hojas_ruta', sa.Column('cobro_chofer_pagado', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('hojas_ruta', sa.Column('fecha_pago_chofer', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('pedidos', 'costo_delivery',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Costo de delivery acordado con el cliente. Cobro aparte, no suma al monto_total.',
               existing_nullable=True)
    op.alter_column('productos', 'peso_bruto',
               existing_type=sa.NUMERIC(precision=8, scale=3),
               comment=None,
               existing_comment='Peso bruto en kg (producto + empaque). Usado para asignación de vehículos en delivery.',
               existing_nullable=True)
    op.create_index(op.f('ix_roles_nombre'), 'roles', ['nombre'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_nombre'), table_name='roles')
    op.alter_column('productos', 'peso_bruto',
               existing_type=sa.NUMERIC(precision=8, scale=3),
               comment='Peso bruto en kg (producto + empaque). Usado para asignación de vehículos en delivery.',
               existing_nullable=True)
    op.alter_column('pedidos', 'costo_delivery',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Costo de delivery acordado con el cliente. Cobro aparte, no suma al monto_total.',
               existing_nullable=True)
    op.drop_column('hojas_ruta', 'fecha_pago_chofer')
    op.drop_column('hojas_ruta', 'cobro_chofer_pagado')
    op.drop_column('hojas_ruta', 'monto_cobro_chofer')
    op.drop_column('hojas_ruta', 'tarifa_chofer')
    op.drop_column('hojas_ruta', 'tipo_cobro_chofer')
    # ### end Alembic commands ###
