"""add_vehiculos_and_update_hojas_ruta

Revision ID: cac50f9a5746
Revises: ea8f68ff3a2c
Create Date: 2026-03-09 19:07:07.375280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cac50f9a5746'
down_revision: Union[str, None] = 'ea8f68ff3a2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipo_vehiculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_tipo_vehiculo_id'), 'tipo_vehiculo', ['id'], unique=False)
    op.create_table('vehiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('patente', sa.String(length=20), nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('modelo', sa.String(length=100), nullable=True),
    sa.Column('anio', sa.Integer(), nullable=True),
    sa.Column('capacidad_kg', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('tipo_vehiculo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tipo_vehiculo_id'], ['tipo_vehiculo.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'patente', name='uq_vehiculo_patente_tenant')
    )
    op.create_index(op.f('ix_vehiculos_id'), 'vehiculos', ['id'], unique=False)
    op.create_index(op.f('ix_vehiculos_tenant_id'), 'vehiculos', ['tenant_id'], unique=False)
    op.add_column('hojas_ruta', sa.Column('vehiculo_id', sa.Integer(), nullable=True))
    op.add_column('hojas_ruta', sa.Column('chofer_id', sa.Integer(), nullable=True))
    op.alter_column('hojas_ruta', 'chofer_nombre',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.create_foreign_key(None, 'hojas_ruta', 'users', ['chofer_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'hojas_ruta', 'vehiculos', ['vehiculo_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('hojas_ruta', 'patente')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hojas_ruta', sa.Column('patente', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'hojas_ruta', type_='foreignkey')
    op.drop_constraint(None, 'hojas_ruta', type_='foreignkey')
    op.alter_column('hojas_ruta', 'chofer_nombre',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.drop_column('hojas_ruta', 'chofer_id')
    op.drop_column('hojas_ruta', 'vehiculo_id')
    op.drop_index(op.f('ix_vehiculos_tenant_id'), table_name='vehiculos')
    op.drop_index(op.f('ix_vehiculos_id'), table_name='vehiculos')
    op.drop_table('vehiculos')
    op.drop_index(op.f('ix_tipo_vehiculo_id'), table_name='tipo_vehiculo')
    op.drop_table('tipo_vehiculo')
    # ### end Alembic commands ###
