"""Add_orden_produccion_tables

Revision ID: d4a428b8aba2
Revises: e975bf4eaa98
Create Date: 2025-12-16 14:11:29.260086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4a428b8aba2'
down_revision: Union[str, None] = 'e975bf4eaa98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ordenes_produccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('local_id', sa.Integer(), nullable=False),
    sa.Column('fecha_programada', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_finalizacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['local_id'], ['locales.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ordenes_produccion_id'), 'ordenes_produccion', ['id'], unique=False)
    op.create_table('detalles_orden_produccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orden_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('unidad_medida_id', sa.Integer(), nullable=False),
    sa.Column('cantidad_programada', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('cantidad_producida', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.ForeignKeyConstraint(['orden_id'], ['ordenes_produccion.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['unidad_medida_id'], ['unidades_medida.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detalles_orden_produccion_id'), 'detalles_orden_produccion', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detalles_orden_produccion_id'), table_name='detalles_orden_produccion')
    op.drop_table('detalles_orden_produccion')
    op.drop_index(op.f('ix_ordenes_produccion_id'), table_name='ordenes_produccion')
    op.drop_table('ordenes_produccion')
    # ### end Alembic commands ###
