"""add_visible_en_pos_to_canales_venta

Revision ID: dbd9fc2192b9
Revises: 621ed46446aa
Create Date: 2026-03-25 12:15:52.213580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbd9fc2192b9'
down_revision: Union[str, None] = '621ed46446aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('canales_venta', sa.Column('visible_en_pos', sa.Boolean(), nullable=False, server_default='true'))
    op.execute("UPDATE canales_venta SET visible_en_pos = false WHERE codigo = 'LANDING'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('canales_venta', 'visible_en_pos')
    # ### end Alembic commands ###
