"""add_tipos_pedido_table_and_foreign_key

Revision ID: e05801cae0ac
Revises: 7ce7243d1bbd
Create Date: 2026-01-06 16:26:37.426450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e05801cae0ac'
down_revision: Union[str, None] = '7ce7243d1bbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipos_pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipos_pedido_codigo'), 'tipos_pedido', ['codigo'], unique=True)
    op.create_index(op.f('ix_tipos_pedido_id'), 'tipos_pedido', ['id'], unique=False)
    op.create_index(op.f('ix_tipos_pedido_nombre'), 'tipos_pedido', ['nombre'], unique=False)
    
    # Insertar datos iniciales
    tipos_pedido_table = sa.table('tipos_pedido',
        sa.column('id', sa.Integer),
        sa.column('codigo', sa.String),
        sa.column('nombre', sa.String),
        sa.column('descripcion', sa.String),
        sa.column('activo', sa.Boolean)
    )
    
    op.bulk_insert(tipos_pedido_table, [
        {'id': 1, 'codigo': 'PRODUCTOS', 'nombre': 'Productos Regulares', 'descripcion': 'Pedidos de productos del inventario regular', 'activo': True},
        {'id': 2, 'codigo': 'CAJAS_VARIABLES', 'nombre': 'Cajas Variables', 'descripcion': 'Pedidos de cajas de carne con peso variable', 'activo': True}
    ])
    
    # Agregar columna nullable primero
    op.add_column('pedidos', sa.Column('tipo_pedido_id', sa.Integer(), nullable=True))
    
    # Actualizar pedidos existentes con tipo PRODUCTOS (default)
    pedidos_table = sa.table('pedidos',
        sa.column('tipo_pedido_id', sa.Integer)
    )
    op.execute(pedidos_table.update().values(tipo_pedido_id=1))
    
    # Ahora hacer el campo NOT NULL
    op.alter_column('pedidos', 'tipo_pedido_id', nullable=False)
    
    op.create_foreign_key(None, 'pedidos', 'tipos_pedido', ['tipo_pedido_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pedidos', type_='foreignkey')
    op.drop_column('pedidos', 'tipo_pedido_id')
    op.drop_index(op.f('ix_tipos_pedido_nombre'), table_name='tipos_pedido')
    op.drop_index(op.f('ix_tipos_pedido_id'), table_name='tipos_pedido')
    op.drop_index(op.f('ix_tipos_pedido_codigo'), table_name='tipos_pedido')
    op.drop_table('tipos_pedido')
    # ### end Alembic commands ###
