"""Agregar sistema de producción: categorías, tipos, unidades, recetas

Revision ID: e975bf4eaa98
Revises: 8ba74120e022
Create Date: 2025-12-10 13:31:34.423083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e975bf4eaa98'
down_revision: Union[str, None] = '8ba74120e022'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Crear tablas maestras
    op.create_table('categorias_producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('puntos_fidelidad', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categorias_producto_codigo'), 'categorias_producto', ['codigo'], unique=True)
    op.create_index(op.f('ix_categorias_producto_id'), 'categorias_producto', ['id'], unique=False)
    op.create_index(op.f('ix_categorias_producto_nombre'), 'categorias_producto', ['nombre'], unique=False)
    
    op.create_table('tipos_producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipos_producto_codigo'), 'tipos_producto', ['codigo'], unique=True)
    op.create_index(op.f('ix_tipos_producto_id'), 'tipos_producto', ['id'], unique=False)
    
    op.create_table('unidades_medida',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('simbolo', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('factor_conversion', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('unidad_base_id', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['unidad_base_id'], ['unidades_medida.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unidades_medida_codigo'), 'unidades_medida', ['codigo'], unique=True)
    op.create_index(op.f('ix_unidades_medida_id'), 'unidades_medida', ['id'], unique=False)
    
    # 2. Insertar datos por defecto en tablas maestras
    op.execute("""
        INSERT INTO categorias_producto (codigo, nombre, descripcion, puntos_fidelidad, activo) VALUES
        ('GENERAL', 'General', 'Categoría general por defecto', 0, true);
    """)
    
    op.execute("""
        INSERT INTO tipos_producto (codigo, nombre, descripcion, activo) VALUES
        ('MATERIA_PRIMA', 'Materia Prima', 'Productos comprados para uso/venta', true),
        ('PRODUCTO_ELABORADO', 'Producto Elaborado', 'Productos fabricados internamente', true);
    """)
    
    op.execute("""
        INSERT INTO unidades_medida (codigo, nombre, simbolo, tipo, factor_conversion, unidad_base_id, activo) VALUES
        ('UNIDAD', 'Unidad', 'un', 'CANTIDAD', 1, NULL, true),
        ('KILOGRAMO', 'Kilogramo', 'kg', 'PESO', 1, NULL, true),
        ('GRAMO', 'Gramo', 'g', 'PESO', 1000, 2, true),
        ('LITRO', 'Litro', 'L', 'VOLUMEN', 1, NULL, true),
        ('MILILITRO', 'Mililitro', 'ml', 'VOLUMEN', 1000, 4, true);
    """)
    
    # 3. Crear tablas de recetas
    op.create_table('recetas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('rendimiento', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('unidad_rendimiento_id', sa.Integer(), nullable=False),
    sa.Column('costo_total_calculado', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('costo_unitario_calculado', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unidad_rendimiento_id'], ['unidades_medida.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recetas_id'), 'recetas', ['id'], unique=False)
    
    op.create_table('ingredientes_receta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receta_id', sa.Integer(), nullable=False),
    sa.Column('producto_ingrediente_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('unidad_medida_id', sa.Integer(), nullable=False),
    sa.Column('costo_unitario_referencia', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('costo_total_calculado', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('notas', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['producto_ingrediente_id'], ['productos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['receta_id'], ['recetas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unidad_medida_id'], ['unidades_medida.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredientes_receta_id'), 'ingredientes_receta', ['id'], unique=False)
    
    # 4. Agregar columnas a productos (NULLABLE primero)
    op.add_column('locales', sa.Column('activo', sa.Boolean(), nullable=True, server_default='true'))
    
    op.add_column('productos', sa.Column('categoria_id', sa.Integer(), nullable=True))
    op.add_column('productos', sa.Column('tipo_producto_id', sa.Integer(), nullable=True))
    op.add_column('productos', sa.Column('unidad_medida_id', sa.Integer(), nullable=True))
    op.add_column('productos', sa.Column('precio_compra', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('productos', sa.Column('costo_fabricacion', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('productos', sa.Column('es_vendible', sa.Boolean(), nullable=True, server_default='true'))
    op.add_column('productos', sa.Column('es_vendible_web', sa.Boolean(), nullable=True, server_default='false'))
    op.add_column('productos', sa.Column('es_ingrediente', sa.Boolean(), nullable=True, server_default='false'))
    op.add_column('productos', sa.Column('tiene_receta', sa.Boolean(), nullable=True, server_default='false'))
    op.add_column('productos', sa.Column('activo', sa.Boolean(), nullable=True, server_default='true'))
    
    # 5. Actualizar productos existentes con valores por defecto
    op.execute("""
        UPDATE productos SET
            categoria_id = 1,  -- GENERAL
            tipo_producto_id = 1,  -- MATERIA_PRIMA
            unidad_medida_id = 1  -- UNIDAD
        WHERE categoria_id IS NULL;
    """)
    
    # 6. Hacer columnas NOT NULL
    op.alter_column('productos', 'categoria_id', nullable=False)
    op.alter_column('productos', 'tipo_producto_id', nullable=False)
    op.alter_column('productos', 'unidad_medida_id', nullable=False)
    
    # 7. Otros cambios en productos
    op.alter_column('productos', 'descripcion',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_constraint('productos_sku_key', 'productos', type_='unique')
    op.create_index(op.f('ix_productos_sku'), 'productos', ['sku'], unique=True)
    
    # 8. Crear foreign keys
    op.create_foreign_key(None, 'productos', 'tipos_producto', ['tipo_producto_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'productos', 'unidades_medida', ['unidad_medida_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'productos', 'categorias_producto', ['categoria_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'productos', type_='foreignkey')
    op.drop_constraint(None, 'productos', type_='foreignkey')
    op.drop_constraint(None, 'productos', type_='foreignkey')
    op.drop_index(op.f('ix_productos_sku'), table_name='productos')
    op.create_unique_constraint('productos_sku_key', 'productos', ['sku'])
    op.alter_column('productos', 'descripcion',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('productos', 'activo')
    op.drop_column('productos', 'tiene_receta')
    op.drop_column('productos', 'es_ingrediente')
    op.drop_column('productos', 'es_vendible_web')
    op.drop_column('productos', 'es_vendible')
    op.drop_column('productos', 'costo_fabricacion')
    op.drop_column('productos', 'precio_compra')
    op.drop_column('productos', 'unidad_medida_id')
    op.drop_column('productos', 'tipo_producto_id')
    op.drop_column('productos', 'categoria_id')
    op.drop_column('locales', 'activo')
    op.drop_index(op.f('ix_ingredientes_receta_id'), table_name='ingredientes_receta')
    op.drop_table('ingredientes_receta')
    op.drop_index(op.f('ix_recetas_id'), table_name='recetas')
    op.drop_table('recetas')
    op.drop_index(op.f('ix_unidades_medida_id'), table_name='unidades_medida')
    op.drop_index(op.f('ix_unidades_medida_codigo'), table_name='unidades_medida')
    op.drop_table('unidades_medida')
    op.drop_index(op.f('ix_tipos_producto_id'), table_name='tipos_producto')
    op.drop_index(op.f('ix_tipos_producto_codigo'), table_name='tipos_producto')
    op.drop_table('tipos_producto')
    op.drop_index(op.f('ix_categorias_producto_nombre'), table_name='categorias_producto')
    op.drop_index(op.f('ix_categorias_producto_id'), table_name='categorias_producto')
    op.drop_index(op.f('ix_categorias_producto_codigo'), table_name='categorias_producto')
    op.drop_table('categorias_producto')
    # ### end Alembic commands ###
