"""add_hojas_ruta_system

Revision ID: ea8f68ff3a2c
Revises: 8cf98e32f680
Create Date: 2026-03-09 18:26:58.067408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea8f68ff3a2c'
down_revision: Union[str, None] = '8cf98e32f680'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hojas_ruta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('chofer_nombre', sa.String(length=200), nullable=False),
    sa.Column('patente', sa.String(length=20), nullable=True),
    sa.Column('capacidad_kg', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'EN_RUTA', 'COMPLETADA', name='estadohojaruta'), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_salida', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_retorno', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hojas_ruta_id'), 'hojas_ruta', ['id'], unique=False)
    op.create_index(op.f('ix_hojas_ruta_tenant_id'), 'hojas_ruta', ['tenant_id'], unique=False)
    op.create_table('hoja_ruta_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hoja_ruta_id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('entregado', sa.Boolean(), nullable=False),
    sa.Column('fecha_entrega', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notas_entrega', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['hoja_ruta_id'], ['hojas_ruta.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hoja_ruta_items_id'), 'hoja_ruta_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hoja_ruta_items_id'), table_name='hoja_ruta_items')
    op.drop_table('hoja_ruta_items')
    op.drop_index(op.f('ix_hojas_ruta_tenant_id'), table_name='hojas_ruta')
    op.drop_index(op.f('ix_hojas_ruta_id'), table_name='hojas_ruta')
    op.drop_table('hojas_ruta')
    # ### end Alembic commands ###
