"""add usuario_finalizador_id to solicitudes_transferencia

Revision ID: f034a5f09e4c
Revises: 49a92ddfe08e
Create Date: 2026-02-27 17:32:06.915159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f034a5f09e4c'
down_revision: Union[str, None] = '49a92ddfe08e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solicitudes_transferencia', sa.Column('usuario_finalizador_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'solicitudes_transferencia', 'users', ['usuario_finalizador_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'solicitudes_transferencia', type_='foreignkey')
    op.drop_column('solicitudes_transferencia', 'usuario_finalizador_id')
    # ### end Alembic commands ###
