"""Agregar tabla TipoProveedor y relacion con Proveedor

Revision ID: f174fd5be22a
Revises: 6f75a40772fc
Create Date: 2026-01-05 13:41:18.923802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f174fd5be22a'
down_revision: Union[str, None] = '6f75a40772fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipos_proveedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipos_proveedor_codigo'), 'tipos_proveedor', ['codigo'], unique=True)
    op.create_index(op.f('ix_tipos_proveedor_id'), 'tipos_proveedor', ['id'], unique=False)
    op.add_column('proveedores', sa.Column('tipo_proveedor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'proveedores', 'tipos_proveedor', ['tipo_proveedor_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'proveedores', type_='foreignkey')
    op.drop_column('proveedores', 'tipo_proveedor_id')
    op.drop_index(op.f('ix_tipos_proveedor_id'), table_name='tipos_proveedor')
    op.drop_index(op.f('ix_tipos_proveedor_codigo'), table_name='tipos_proveedor')
    op.drop_table('tipos_proveedor')
    # ### end Alembic commands ###
