"""Agregar local_defecto_id a users

Revision ID: fd6f9456eefc
Revises: becf5fa373d3
Create Date: 2026-01-02 20:39:03.451549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd6f9456eefc'
down_revision: Union[str, None] = 'becf5fa373d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('local_defecto_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'locales', ['local_defecto_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'local_defecto_id')
    # ### end Alembic commands ###
